### ISSUE TITLE
Please incorporate Alan's version of GnG

### ISSUE THREAD

**Issue by chromestrong** [google/loaner#103]
A past member of the GnG team created a near automated install for GnG for Linux that also included giving a Linux vm image so that all dependencies were covered.  The Code can be found here.  Please incorporate it for Linux deployments it was amazingly easy: https://github.com/kid-yume/gnglinuxdeployment/tree/dev

**Comment by helfrichmichael** [comment]
Since this code was not submitted internally, we cannot use it. Additionally we aren't yet accepting pull requests (hopefully sometime in the future), so this code cannot yet be contributed if they were to create a pull request.

I'll close given the circumstances, but feel free to let me know if you have any further questions.

**Comment by chromestrong** [comment]
I would recommend "Borrowing" from it since its the best GnG version I have seen to date.  Not using it at all would be a mistake.
