### ISSUE TITLE
Completely reset Loaner data/Downgrading issues

### ISSUE THREAD

**Issue by cculler-onix** [google/loaner#105]
Hello, I've taken over maintenance on a few Loaner deployments and I've been experiencing issues and errors related to the associated_fleet attribute on devices on deployments that were deployed with version 0.7.6-alpha. I have not been able to find this version in the repository, as it appears this version was rolled back. There are no customizations to these deployments, and so I tried to revert to version 0.7.3-alpha (the current master version) but I still experienced errors related to the associated_fleet attribute. I attempted to wipe the data for the Loaner application by deleting the BigQuery Loaner dataset and removing all of the DataStore entities. After wiping the data, I attempted to run the bootstrap process again. After bootstrapping again, there were a lot of entities missing from DataStore - such as the CoreEvents kind, Template kind, etc. This caused errors such as the NoEventsError to trigger and report that bootstrapping still needs to be completed. 

Is there a "correct" process for wiping and resetting a Loaner deployment? Is there a documented process to downgrade from the flawed 0.7.6-alpha version?

### Expected Behaviour
The Loaner deployment was expected to work after downgrading from 0.7.6-alpha to 0.7.3-alpha. 
### Actual Behaviour
Loaner deployment does not work, and produces a myriad of errors in StackDriver. 
### Steps to Reproduce
1. Deploy version 0.7.6-alpha (not possible due to this version not existing in the repository anymore)
2. Revert to version 0.7.3

**Comment by helfrichmichael** [comment]
Thanks for reporting this. I can't provide any specific guidance for reverting or downgrading (usually we'd recommend against that since you're potentially affecting the Datastore entity model).

The current version we recommend is our master version. There was a push a while ago that caused some associated_fleet issues, but the latest master push shouldn't have this issue. Additionally when you're updating the serving version are you updating the serving version for each of the services (action-system, default, chrome, endpoints)?

Here is the 0.7.6a commit: https://github.com/google/loaner/commit/16df9a508f61d0ed363a1a517cd8c6778f5271d6#diff-eecff035f2a636bf3d7ef27d96f9d648

You should also flush memcache and indexing if possible to see if that remediates some of the issues.

If you are comfortable blowing away this whole deployment and starting from scratch (this is definitely the nuclear route), you'd need to delete everything in Datastore, flush the memcache, and clear the indexing. Then redeploy and setup as you normally would. Do keep in mind that if you take this approach, it will delete everything from the app (including devices).

**Comment by cculler-onix** [comment]
Flushing memcached after the Datastore wipe allowed the bootstrapping to happen correctly and eliminated the errors that were appearing in StackDriver. However, I am now running into an OAuth issue in the Chrome app. The Chrome app appears to be unable to get an OAuth token. I triple-checked that the Chrome client ID is authorized correctly. I've attached a screenshot of the debug screen from the Chrome app. 
![Polish_20200519_171512369](https://user-images.githubusercontent.com/43762110/82379283-a2c34e80-99f4-11ea-8d19-4c928ecd528b.png)

**Comment by cculler-onix** [comment]
The OAuth issue was resolved and was due to a misconfiguration with the client ID. Thanks!
