### ISSUE TITLE
How to update configuration after bootstrap?

### ISSUE THREAD

**Issue by ConsueloJim** [google/loaner#43]
### Expected Behaviour
Update defaults set in config_defaults.yaml should update the web app

### Actual Behaviour
Still runs old configuration

### Steps to Reproduce
I would like to update the configurations in the config_defaults.yaml file. Do I need to redo the bootstrap process and also redeploy the Chome app in the web store in order to do this? 

I tried updating the file and running bootstrap again without deploying a new version of the chome app to the web store but the configuration did not update. 

I would prefer not to have to redeploy the chrome app every time I want to reconfigure something in the config_default.yaml file is there a way to update the config in the GCP console after deployment?

**Comment by lukehawkins94** [comment]
This just corresponds to what is saved in http://yoururl-appspot.com/configuration, if you open up the config and just change the settings to the defaults you are deploying then that'll have the desired effect you want.

If there are some settings that are not inside there that are on the config_defaults.yaml then you can open up DataStore and try and find the "Kind" such as `ShelfAuditEvent` to change it's value.

I think the config_defaults.yaml is basically designed to stay in your own repo/configs so that if anything goes wrong with your installation you can just deploy it with the same configurations as before.

**Comment by helfrichmichael** [comment]
Going to resolve this since there hasn't been any further update in some time and the previous reply is correct. Thanks and let us know if this isn't resolved.
