### ISSUE TITLE
master branch build failing?

### ISSUE THREAD

**Issue by agosto-raypitmon** [google/loaner#58]
I see that the master branch build is failing since an update 22 days ago. Is anyone going to take a look at that?

Also, I see that the latest release branch (Alpha-0.7.1) hasn't had an update since December. I'm wondering if people should still be using that branch or is master the way to go (assuming it's fixed)?

Thanks!

**Comment by helfrichmichael** [comment]
Ah yeah, that build will likely fail since it's dependent on the latest version of Angular and we haven't gotten that fixed within GitHub.

I think you can aim for the following commit and backwards if you are starting a deployment: 
https://github.com/google/loaner/commit/a63b4c3ce2cc125e223e4aef396215570a18fc00

**Comment by gyoshi02** [comment]
Hi, 
Also trying to use master build, is this still an issue? 
I'm getting 
"ERROR: The Bazel BUILD files appear to be missing."
I'll try latest Alpha, but wanted to be using the latest build for a pilot that will be used on our production domain. 
Thanks,
Grant

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.

The latest version of Grab and Go (master/head) and Bazel 0.26.1 should resolve this issue for you.
