### ISSUE TITLE
Loan Duration Reminder Email not working

### ISSUE THREAD

**Issue by blackrock-gng** [google/loaner#65]

**Comment by gyoshi02** [comment]
I'm having the same issue here. 
Is there anything we can provide? Logs/screenshots ? 
Thanks,

**Comment by David-Promevo** [comment]
Confirming the same issue, you can likely turn it off / on by setting the
Boolean value in GCP > Datastore > Entities > Config > Loan Duration Email

**Comment by blackrock-gng** [comment]
Thanks.  It appears to be working now for us even though we still can't turn the button on.

**Comment by rionellis** [comment]
Yeah there's something wrong where the switch doesn't stay on, but if you check the datastore you can see it's actually enabled.

**Comment by gyoshi02** [comment]
Can you guys please confirm I'm checking in the right section of Datastore config: 
![image](https://user-images.githubusercontent.com/45863342/65173616-00397280-da04-11e9-8b51-e041df700610.png)
![image](https://user-images.githubusercontent.com/45863342/65173637-0e878e80-da04-11e9-9604-b14e8ea78f12.png)
I also checked/updated my config_defaults.yaml, and noticed that I already had this value to true: 
'loan_duration_email': True
Also, is there a way to initiate/generate test emails for the reminder?
Can we modify the loan duration time to 12 hours (0.5) or update the device's loaned out time record to set it as almost expired? 
Trying to get all the minor issues worked out, before we deploy this to a larger group. 
Thanks,

**Comment by rionellis** [comment]
![gng_datastore](https://user-images.githubusercontent.com/52011890/65175500-98d9ed80-da18-11e9-97dc-8a7e494d2f04.PNG)

**Comment by rionellis** [comment]
There you go. Hope that helps. Datastore --> Entities --> Change Kind to Config, and look for name=loan_duration_email if the bool_value = True (it's enabled).

**Comment by helfrichmichael** [comment]
Hi all,

Sorry for the delay here! This was fixed upstream and should be patched in the next push. It looks like the culprit is a config name mismatch. If you want to remediate on the Frontend, please take the following actions that I've defined below.

1. Open loaner/web_app/frontend/src/components/configuration/configuration.ng.html with your favorite editor.
2. Edit line 73 `<mat-slide-toggle name="loan_duration_email_boolean" [(ngModel)]="config.loanDurationReminderEmail"></mat-slide-toggle>` 
to 
`<mat-slide-toggle name="loan_duration_email_boolean" [(ngModel)]="config.loanDurationEmail"></mat-slide-toggle>`
3. Save and redeploy the app!

Looking at https://github.com/google/loaner/blob/master/loaner/web_app/frontend/src/models/config.ts shows that the `loan_duration_email` boolean from the config.list API method relates to the `loanDurationEmail` param of the config class on the Frontend.

Thanks for reporting the issue and let me know if that works for you all or if you hit any issues!

**Comment by gyoshi02** [comment]
Sorry to respond within an older thread, that's been fixed, but is it possible to send from a google group rather than a service account? 
Only reason I ask is that we've been asked to reduce the number of service accounts that we have. 
I've tried switching the values within "loaner/web_app/constants.py" for SEND_EMAIL_AS, but now I'm not getting any emails or notifications for loan duration. 
Thanks,

**Comment by helfrichmichael** [comment]
@gyoshi02 Feel free to file a new issue and we can look into your request. Given that this issue is fixed I'm going to close it out.
