### ISSUE TITLE
[Question] What is the reasoning behind making the OAuth consent screen public 

### ISSUE THREAD

**Issue by CoreyGriffin** [google/loaner#82]
This is just a generic gap in knowledge question that I am looking for more insight on related to this project. 

I noticed this line was taken our of the Setup Docs

> WARNING: The Chrome App will be unable to generate any OAuth tokens if the Application type isn't listed as Public.

What is the reasoning behind requiring this to be public?  I thought the consent screen was more so to restrict the domain for authorizations. If you were restricting these devices to your domain anyways, why cant the screen be set to private?

**Comment by helfrichmichael** [comment]
Sorry for the delayed reply. I never had a chance to dig back into this. I believe it's because of the way in which our apps communicate with these various APIs. I have never seen a successful deployment with the tokens limited to private.

The app is still restricted by domains, etc so there's still inherent checks and balances. I'm going to resolve this, but if you have further questions don't hesitate to re-open.
