### ISSUE TITLE
Behavior expected with user email alias (but valid Google user) in SuperAdmin group

### ISSUE THREAD

**Issue by damionwilliams** [google/loaner#85]
### Expected Behavior
SuperAdmins of given group should have full access to the Grab N Go web interface

### Actual Behavior
SuperAdmins are only allowed user access

### Steps to Reproduce
Set SUPERADMINS_GROUP in constants.py to 'technologyservices@domainparent.org'

Inside technologyservices@domainparent.org there are a number of members who are joined to that group with a membership derived from an alias address. For example:

technologyservices@domainparent.org contains a user member of 
johnsmith@domainsecondary.org - this email address being a valid alias of the actual Google account johnsmith@domainparent.org. 

In this circumstance, no admin rights are granted on the web app.

Is this simple to resolve?

Thank you,
Damion

**Comment by helfrichmichael** [comment]
Does your role account have access to Google Groups, additionally have you confirmed that your current serving version of each App Engine instance are reporting this same SUPERADMINS_GROUP?

You can view this by doing the following:

Visit Google Cloud Platform, open App Engine - Versions. To the right of the serving version, under the diagnose column, click the dropdown and select "Debug". You can then open the constants.py file and review your values.

Finally the only thing I can think of otherwise that might be causing an issue is that I believe you do not need to provide a domain name for the group config as that is inferred.

`IE: SUPERADMINS_GROUP = 'loaner-people'` would resolve to loaner-people@google.com (this isn't a real alias, just an example).

**Comment by helfrichmichael** [comment]
We haven't heard back from you in a while, so I'm going to close out this issue. Let us know if you have any further issues.
